# Generated by Django 5.2.2 on 2025-06-09 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_tool', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('grid_rows', models.PositiveIntegerField()),
                ('grid_cols', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_boards', to=settings.AUTH_USER_MODEL)),
                ('map_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards_on_this_map', to='mapping_tool.map')),
            ],
        ),
        migrations.CreateModel(
            name='Waystone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[('red', 'Czerwony'), ('blue', 'Niebieski'), ('green', 'Zielony'), ('yellow', 'Żółty'), ('purple', 'Fioletowy'), ('orange', 'Pomarańczowy'), ('pink', 'Różowy'), ('cyan', 'Cyjan'), ('brown', 'Brązowy'), ('black', 'Czarny')], max_length=20)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waystones', to='mapping_tool.board')),
            ],
            options={
                'unique_together': {('board', 'row', 'col')},
            },
        ),
    ]
