# Generated by Django 5.2 on 2025-05-03 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name for the background image.', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name).', max_length=255, unique=True)),
                ('image', models.ImageField(help_text='The image file (e.g., JPG, PNG).', upload_to='background_images/')),
                ('description', models.TextField(blank=True, help_text='Optional description of the image.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the image was uploaded.')),
                ('uploader', models.ForeignKey(blank=True, help_text='The user who uploaded this image (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Background Image',
                'verbose_name_plural': 'Background Images',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for this route.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the route.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the route was created.')),
                ('background_image', models.ForeignKey(help_text='The background image for this route.', on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='mapping.backgroundimage')),
                ('user', models.ForeignKey(help_text='The user who created this route.', on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='X coordinate as a fraction (0.0 to 1.0) of the image width.')),
                ('y', models.FloatField(help_text='Y coordinate as a fraction (0.0 to 1.0) of the image height.')),
                ('order', models.PositiveIntegerField(help_text='The sequential order of this point within the route (starts from 0 or 1).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the point was created.')),
                ('route', models.ForeignKey(help_text='The route this point belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='points', to='mapping.route')),
            ],
            options={
                'verbose_name': 'Route Point',
                'verbose_name_plural': 'Route Points',
                'ordering': ['order'],
                'unique_together': {('route', 'order')},
            },
        ),
    ]
